# Note: indentation is VERY important!

parameters:
  build_platform: []
  opt_level: []
  sanitizers: []
  lto: []
  compiler: "gcc"

jobs:
- ${{ each build_platform in parameters.build_platform }}:
  - job: ${{build_platform}}_${{parameters.compiler}}
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
        displayName: apt-get-py3pip

      - ${{ if in(build_platform, 'ARM', 'THUMB', 'AARCH64') }}:
        - script: |
            sudo apt-get install -y qemu-system-arm
          displayName: apt-get-qemu

      - ${{ if in(build_platform, 'ARM', 'THUMB') }}:
        - script: sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi
          displayName: apt-get-toolchain

      - ${{ if eq(parameters.compiler, 'clang') }}:
        - script: |
            sudo apt-get install -y clang-9
            # Make 'clang' be clang-9
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 100
          displayName: apt-get-clang-9

      - ${{ if eq(build_platform, 'AARCH64') }}:
        - template: get-linaro-toolchain.yml
          parameters:
            toolchain_url: 7.4-2019.02/aarch64-elf/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-elf.tar.xz

      - script: |
          # Running it in a venv is the best way to be able to just run 'lit', not some random path or "python -c" invocation.
          pip3 install virtualenv
          python3 -m virtualenv testenv
          source testenv/bin/activate
          pip3 install lit
        displayName: install-lit

      - script: |
          set -ex
          mkdir oclint
          wget -qO- https://github.com/oclint/oclint/releases/download/v0.13.1/oclint-0.13.1-x86_64-linux-4.4.0-112-generic.tar.gz | tar xzf - -C oclint --strip-components=1
          export PATH=$(pwd)/toolchain/bin/:$(pwd)/oclint/bin/:$PATH
          cmake . -DBUILD_PLATFORM=${{build_platform}} -DOPT_LEVEL=0 -DSANITIZERS=ON -DCOMPILER=${{parameters.compiler}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          oclint -p . `find -not \( -path ./oclint -prune \) -not \( -path ./CMakeFiles -prune \) -not \( -path ./demos -prune \) -regex ".*\.c"` -max-priority-1 0 -max-priority-2 0 -max-priority-3 0
        displayName: oclint
        continueOnError: true

      - ${{ each opt_level in parameters.opt_level }}:
        - ${{ each lto in parameters.lto }}:
          - ${{ each sanitizers in parameters.sanitizers }}:
            - script: |
                set -ex
                # Each script has its own environment so we need to do this here
                export PATH=$(pwd)/toolchain/bin/:$PATH
                cmake . -DBUILD_PLATFORM=${{build_platform}} -DOPT_LEVEL=${{opt_level}} -DSANITIZERS=${{sanitizers}} -DLTO=${{lto}}
                make clean
                make make_demos
              displayName: build-O${{opt_level}}_SANITIZERS_${{sanitizers}}_LTO_${{lto}}

            - script: |
                source testenv/bin/activate
                # Don't be fooled, this is actually JUnit format
                lit demos --xunit-xml-output ${{build_platform}}_O${{opt_level}}_SANITIZERS_${{sanitizers}}_LTO_${{lto}}_results.xml
              displayName: test-O${{opt_level}}_SANITIZERS_${{sanitizers}}_LTO_${{lto}}
              # So we'll get a failed build when tests fail
              continueOnError: true

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '*_results.xml'
