language: c
dist: xenial

addons:
  apt:
    packages:
    - qemu-system-arm
    - gcc-arm-none-eabi
    - gcc-aarch64-linux-gnu
    - libnewlib-arm-none-eabi
    - libc6-dev-arm64-cross

script:
  - cmake . -DBUILD_PLATFORM=arm
  - make
  - make clean
  - rm -rf CMakeCache.txt CMakeFiles/
  - cmake . -DBUILD_PLATFORM=aarch64
  - make
