language: c

addons:
  apt:
    packages:
    - cmake
    - qemu-system-arm
    - libc6-dev
    - gcc-arm-none-eabi
    - gcc-aarch64-linux-gnu

script:
  - cmake . -DBUILD_PLATFORM=arm
  - make
  - make clean
  - rm -rf CMakeCache.txt CMakeFiles/
  - cmake . -DBUILD_PLATFORM=aarch64
  - make
