language: c
dist: xenial

matrix:
  include:
    - env: BUILD_PLATFORM=arm OPT_LEVEL=0
      addons: &arm
        apt:
          packages:
            - qemu-system-arm
            - gcc-arm-none-eabi
            - libnewlib-arm-none-eabi
    - env: BUILD_PLATFORM=arm OPT_LEVEL=3
      addons: *arm
    - env: BUILD_PLATFORM=arm OPT_LEVEL=s
      addons: *arm

    #Same tools for arm/thumb builds
    - env: BUILD_PLATFORM=thumb OPT_LEVEL=0
      addons: *arm
    - env: BUILD_PLATFORM=thumb OPT_LEVEL=3
      addons: *arm
    - env: BUILD_PLATFORM=thumb OPT_LEVEL=s
      addons: *arm

    - env: BUILD_PLATFORM=aarch64 OPT_LEVEL=0
      addons: &aarch64
        apt:
          packages:
            - qemu-system-arm
            - gcc-aarch64-linux-gnu
            - libc6-dev-arm64-cross
    - env: BUILD_PLATFORM=aarch64 OPT_LEVEL=3
      addons: *aarch64
    - env: BUILD_PLATFORM=aarch64 OPT_LEVEL=s
      addons: *aarch64

script:
  - cmake . -DBUILD_PLATFORM=$BUILD_PLATFORM -DOPT_LEVEL=$OPT_LEVEL
  - make
