# Note: indentation matters!
# Note: parameters are case sensitive

jobs:
  - template: azure-job.yml
    parameters:
      build_platform: [ARM, THUMB, AARCH64]
      opt_level: [0, s, 3]
      ubsan: [OFF, ON]
