name: build_and_test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_platform: ["ARM", "THUMB", "AARCH64"]

    steps:
    - uses: actions/checkout@v2

    - name: Apt Installs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip ccache expect qemu-system-arm
        echo "CCACHE_DIR=$(pwd)/.ccache" >> $GITHUB_ENV

    - if: matrix.build_platform == 'AARCH64'
      name: Export Toolchain URL
      run: |
        echo "TOOLCHAIN_URL=https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz" >> $GITHUB_ENV

    - if: matrix.build_platform == 'ARM' || matrix.build_platform == 'THUMB'
      name: Export Toolchain URL
      run: |
        echo "TOOLCHAIN_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2" >> $GITHUB_ENV

    - name: Download Toolchain
      run: |
        mkdir toolchain
        wget --quiet $TOOLCHAIN_URL
        tar xaf $(basename $TOOLCHAIN_URL) -C toolchain --strip-components=1
        echo "PATH=$(pwd)/toolchain/bin/:$PATH" >> $GITHUB_ENV

    - name: Install Lit
      run: |
        # Required for distlib, used by virtualenv
        pip3 install setuptools wheel
        # A venv is the best way to be sure where 'lit' is located after install
        pip3 install virtualenv
        python3 -m virtualenv testenv
        source testenv/bin/activate
        pip3 install lit

    - name: Build
      env:
        OPT_LEVELS: 0 S 3
        SANITIZERS: OFF ON
        LTO: OFF ON
        run: |
          for opt_level in $OPT_LEVELS; do
            for sanitizers in $SANITIZERS; do
              for lto in $LTO; do
                # TODO: some kind of for loop or matrix?
                mkdir build_$opt_level_$sanitizers_$lto
                cd build_$opt_level_$sanitizers_$lto
                ccache -z
                cmake -DBUILD_PLATFORM=${{ matrix.build_platform }} -DOPT_LEVEL=$opt_level -DSANITIZERS=$sanitizers -DLTO=$lto ../
                make -j$(nproc) make_demos
                ccache -s
              done
            done
          done

    - name: Test
      run: |
        source testenv/bin/activate
        cd build_O0_OFF_OFF
        # TODO: With multiple threads we sometimes get an error reading progress file
        lit ../demos/ --xunit-xml-output results.xml -a -j1

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v1
      with:
        report_paths: '**/results.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: ${{ matrix.build_platform }}_O0_SANITIZERS_OFF_LTO_OFF
